"use client";
import { useState } from "react";

const metrics = [["25/day → 3/month","BH tickets reduced"],["98.6%","Gainwell SLA"],["99.6%","Cognizant SLA"],["17 KPIs","Executive reporting"],["160+","Dashboard users"]];
const experience = [
 ["2023 — Present","Gainwell Technologies","Senior Business Analyst","Medicaid MMIS/MES requirements, claims, encounters, configuration alignment, UAT, traceability, RAID management, and cross-functional delivery."],
 ["2021 — 2023","Cognizant Technology Solutions","Senior IT Business Analyst / QNXT Application Support","Supported QNXT enrollment, billing, claims, members, EDI, releases, testing, defects, and enhancements at 99.6% SLA performance."],
 ["2018 — 2021","CVS Health / Aetna / Mercy Care","Network Development & Contracting Business Analyst","Provider network, credentialing, DDD implementation, HEDIS/Stars, value-based care, FWA, and executive Tableau reporting."],
 ["2003 — 2019","Magellan Healthcare","Provider Data Analyst","Behavioral health provider data, benefit logic, pricing, prior authorization, QA, and SQL claims analysis."]
];
const projects = [
 {type:"In development · Coming soon",title:"Claims Denial Intelligence",tools:"Python · SQL · Power BI",text:"An active analytics project examining claim-denial trends, root causes, provider patterns, and financial exposure through a structured investigation and interactive dashboard.",result:"Planned deliverable: a documented, repeatable workflow that turns denial data into prioritized operational actions and measurable opportunities.",url:null,linkLabel:null},
 {type:"In development · Coming soon",title:"Claims Anomaly Triage",tools:"SAS · Python · SQL",text:"An active analytics project focused on data-quality profiling and explainable detection of unusual claim and billing patterns across large healthcare datasets.",result:"Planned deliverable: a transparent triage method that helps analysts focus review on credible, high-value exceptions while preserving human validation.",url:null,linkLabel:null},
 {type:"Professional case study",title:"Medicaid & CHIP Unwinding Analysis",tools:"Python · pandas · SciPy · Seaborn",text:"Analyzed CMS state-level renewal, procedural termination, ex parte renewal, and call-center metrics to test how operational friction affected coverage continuity.",result:"Found that procedural losses were driven by broader administrative barriers—not call-center performance alone—and identified automation and proactive outreach as the strongest operational levers.",url:"https://www.kaggle.com/code/stevenogilbert/cms-medicaid-chip-unwinding-state-by-state-oper",linkLabel:"View analysis on Kaggle ↗"},
 {type:"Featured professional case study",title:"Claim Adjudication Configuration & Root-Cause Analysis",tools:"COB · FQHC · EVV · SQL · RCA · Testing",text:"Three complex synthetic Medicaid claim investigations tracing unexpected payments and denials through business rules, configuration, provider contracts, pricing, edits, and supporting data.",result:"Demonstrates a repeatable method for isolating claim-payment defects, documenting corrective action, and validating results through functional and regression testing.",url:"https://github.com/notsogilbert/claim-adjudication-rca/tree/main",linkLabel:"View project on GitHub ↗"}
];
const questions = {
 denial:{label:"Why did denials increase?",steps:[["SQL","Join claims, edits, benefits, contracts, and provider data."],["SAS","Profile enterprise data and validate the signal."],["R","Test which patterns are statistically meaningful."],["Python","Automate exception triage and reusable workflows."],["Power BI","Turn findings into decisions and accountable actions."]]},
 network:{label:"Where are network gaps?",steps:[["SQL","Build a trusted provider, specialty, member, and geography dataset."],["SAS","Validate coverage logic and incomplete attributes."],["R","Analyze access patterns and underserved populations."],["Python","Automate distance, capacity, and adequacy checks."],["Tableau","Show where access risk is concentrated and why."]]},
 sla:{label:"What is slowing operations?",steps:[["SQL","Extract inventory, aging, defect, and milestone data."],["SAS","Reconcile measures and establish trusted baselines."],["R","Separate normal variation from meaningful shifts."],["Python","Flag emerging bottlenecks automatically."],["Power BI","Connect SLA risk to workload and intervention."]]}
};
const skills=["Python","SAS","R","SQL","Power BI","Tableau","Facets","QNXT","MMIS / MES"];
const certifications = [
 {name:"AI Professional Certificate",url:"https://coursera.org/share/b2a912dccb1239ff8becc93696badfc3"},
 {name:"Business Intelligence Certificate",url:null},
 {name:"Data Analytics Certificate",url:"https://coursera.org/share/6d10f4b92b85e946ae4dc015f9116da0"}
];

export default function Home(){
 const [q,setQ]=useState<keyof typeof questions>("denial");
 const [copied,setCopied]=useState(false);
 const copyEmail=async()=>{await navigator.clipboard.writeText("mackartist@live.com");setCopied(true);window.setTimeout(()=>setCopied(false),2500)};
 return <main>
  <nav><a className="brand" href="#top"><span>SG</span><b>Steven Gilbert</b></a><div className="navlinks"><a href="#expertise">Expertise</a><a href="#analytics">Analytics</a><a href="#work">Work</a><a href="#experience">Experience</a></div><a className="talk" href="#contact">Let&apos;s talk ↓</a></nav>
  <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow live">Open to remote U.S. opportunities</p><h1>Healthcare systems.<br/><em>Sharper decisions.</em></h1><p className="lead">I translate complex claims, provider, member, and operational data into solutions leaders can trust—and teams can deliver.</p><div className="actions"><a className="btn primary" href="#work">Explore my work ↓</a><a className="btn ghost" href="#contact">Request my résumé ↓</a></div><div className="meta"><span>Maricopa, Arizona</span><span>Healthcare BA / BSA</span><span>Data & BI</span></div></div>
   <aside className="executiveSnapshot" aria-label="Executive career snapshot"><header><p className="eyebrow">EXECUTIVE CAREER SNAPSHOT</p><span>HEALTHCARE · SYSTEMS · DATA</span></header><div className="snapshotLead"><b>15+ years</b><p>Healthcare operations, business systems and analytics experience</p></div><div className="snapshotMetrics"><div><b>25/day → 3/month</b><span>Configuration tickets</span></div><div><b>98.6%</b><span>Gainwell SLA</span></div><div><b>99.6%</b><span>Cognizant SLA</span></div></div><div className="snapshotGroups"><div><small>FOCUS</small><p>Medical Claims Analytics · Healthcare BA/BSA · Business Intelligence</p></div><div><small>PLATFORMS</small><p>Facets · QNXT · NetworX · MMIS/MES</p></div><div><small>CLAIMS</small><p>Claim Payment · Utilization · Provider Billing · Code Edits · Payment Integrity</p></div><div><small>ANALYTICS</small><p>Python · SAS · R · SQL · Power BI · Tableau · Azure Databricks</p></div></div><footer><a href="#featured-insight">Featured insight ↓</a><a href="https://www.linkedin.com/in/steven-gilbert-a7980116a" target="_blank" rel="noreferrer">LinkedIn ↗</a></footer></aside>
  </section>
  <div className="ticker"><div>{[...skills,...skills].map((s,i)=><span key={i}>{s}<b>✦</b></span>)}</div></div>
  <section className="section light intro" id="expertise"><div><p className="eyebrow blue">01 / POSITIONING</p><h2>The translator between<br/>operations, data, and delivery.</h2></div><div className="introText"><p>Senior healthcare technology professional supporting Medicaid, Medicare, Commercial, and Exchange operations. I connect business policy to system behavior, data evidence, and clear delivery requirements.</p><div className="caps">{["Claims & payment integrity","MMIS / MES modernization","Provider & network data","Requirements & UAT","Executive analytics","Cross-functional leadership"].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="personalAbout" aria-labelledby="about-me-title"><div><p className="eyebrow">ABOUT ME</p><h2 id="about-me-title">Curious by nature.<br/><em>Always building.</em></h2></div><div><p>I am naturally curious and committed to continuous self-learning. I enjoy understanding how things work—not only in healthcare systems and data, but also in everyday life.</p><p>Outside of work, I handle many of my own home, automobile, gadget, and electronic repairs. I enjoy taking things apart, finding the source of a problem, and carefully putting everything back together. I also enjoy building apps and webpages, turning an idea into something useful and functional.</p><p>That same curiosity shapes my professional approach: understand the system, investigate the evidence, find the root cause, and develop a practical solution.</p><div className="aboutTraits"><span>Self-learning</span><span>Hands-on problem solving</span><span>Apps &amp; webpages</span><span>Root-cause thinking</span></div></div></section>
  <section className="section analytics" id="analytics"><div className="sectionHead"><div><p className="eyebrow">02 / ANALYTICS</p><h2>One business question.<br/><em>A connected toolset.</em></h2></div><p>SAS, R, Python, and SQL are not résumé decoration. Each plays a distinct role in moving from raw healthcare data to a defensible decision.</p></div><div className="tabs">{(Object.keys(questions) as (keyof typeof questions)[]).map(k=><button className={q===k?"active":""} onClick={()=>setQ(k)} key={k}>{questions[k].label}</button>)}</div><div className="pipeline">{questions[q].steps.map(([tool,text],i)=><article key={tool}><small>0{i+1}</small><h3>{tool}</h3><p>{text}</p></article>)}</div></section>
  <section className="evidence" aria-labelledby="evidence-title"><div><p className="eyebrow blue">ANALYTICAL DELIVERY</p><h2 id="evidence-title">From raw data to accountable action.</h2><p>A practical, repeatable approach that connects technical analysis to business decisions while keeping quality, traceability, and communication visible at every step.</p></div><ol><li><span>01</span><b>Data extraction</b><p>Integrate claims, member, provider, benefit, contract, and operational data.</p></li><li><span>02</span><b>QA review</b><p>Reconcile totals, validate logic, document exceptions, and establish a trusted baseline.</p></li><li><span>03</span><b>Root-cause analysis</b><p>Isolate patterns across payment rules, code edits, utilization, and provider behavior.</p></li><li><span>04</span><b>Stakeholder presentation</b><p>Translate technical findings for business, operations, technology, and leadership audiences.</p></li><li><span>05</span><b>Issue closure</b><p>Coordinate decisions, corrective action, testing, and verification through resolution.</p></li><li><span>06</span><b>Documentation</b><p>Preserve methods, findings, decisions, user guidance, and repeatable controls.</p></li></ol></section>
  <section className="impact"><p className="eyebrow">VERIFIED IMPACT</p><div>{metrics.map(([v,l])=><article key={v}><b>{v}</b><span>{l}</span></article>)}</div></section>
  <section className="section light" id="work"><div className="sectionHead dark"><div><p className="eyebrow blue">03 / SELECTED WORK</p><h2>Evidence over adjectives.</h2></div><p>Completed work is supported by evidence. Active projects are identified clearly and show the capabilities currently being developed.</p></div><div className="projects">{projects.map((p,i)=><article key={p.title}><header><span>{p.type}</span><b>0{i+1}</b></header><h3>{p.title}</h3><p>{p.text}</p><div className="tools">{p.tools}</div><footer><small>{p.type.startsWith("In development")?"PLANNED DELIVERABLE":"VERIFIED OUTCOME"}</small><p>{p.result}</p>{p.url&&p.linkLabel&&<a className="projectLink" href={p.url} target="_blank" rel="noreferrer" aria-label={`Open ${p.title}`}>{p.linkLabel}</a>}</footer></article>)}</div></section>
  <section className="section flagship" id="claim-adjudication">
   <div className="flagshipHead"><div><p className="eyebrow blue">FEATURED PROFESSIONAL CASE STUDY</p><h2>Claim Adjudication Configuration<br/><em>&amp; Root-Cause Analysis</em></h2></div><p>Three complex synthetic Medicaid claim investigations tracing unexpected payments and denials through business rules, configuration, provider contracts, pricing, edits, and supporting data.</p></div>
   <div className="flagshipFlow" role="img" aria-label="Workflow from business rule through configuration, claim outcome, SQL root-cause analysis, testing, and resolution"><svg viewBox="0 0 1140 170" aria-hidden="true"><defs><linearGradient id="flowLine" x1="0" x2="1"><stop stopColor="#3978e8"/><stop offset="1" stopColor="#19aaa7"/></linearGradient></defs><path d="M90 84H1050" stroke="url(#flowLine)" strokeWidth="3"/>{[["Business Rule",90],["Configuration",250],["Claim",410],["Unexpected Result",570],["SQL + RCA",730],["Test Case",890],["Resolution",1050]].map(([label,x],i)=><g key={String(label)}><circle cx={Number(x)} cy="84" r="25" fill="#f7fbff" stroke={i===3?"#d84f62":"#3978e8"} strokeWidth="3"/><text x={Number(x)} y="89" textAnchor="middle" fontSize="13" fontWeight="800" fill="#07111f">{i+1}</text><text x={Number(x)} y={i%2===0?35:145} textAnchor="middle" fontSize="14" fontWeight="750" fill="#23384d">{label}</text></g>)}</svg></div>
   <div className="flagshipLayers"><article><span>PROJECT OVERVIEW</span><h3>From claim result to verified resolution</h3><p>Follow three synthetic claim scenarios through the business objective, investigation, root cause, corrective action, functional testing, regression testing, and business value.</p></article><article><span>COMPLETE SUPPORTING EVIDENCE</span><h3>Review the work on GitHub</h3><p>Explore the selected SQL, requirements, configuration logic, defect documentation, test cases, and regression evidence in the completed project repository.</p><a className="projectLink" href="https://github.com/notsogilbert/claim-adjudication-rca/tree/main" target="_blank" rel="noreferrer">View complete project on GitHub ↗</a></article></div>
   <div className="flagshipTags">{["COB","Benefits","EVV","FQHC","CARC / RARC","Pricing","Provider Contracts","SQL","RCA","UAT"].map(x=><span key={x}>{x}</span>)}</div>
  </section>
  <section className="section featuredInsight" id="featured-insight">
   <div className="insightKicker"><p className="eyebrow">FEATURED PROFESSIONAL INSIGHT</p><span>AI · ANALYTICS · HUMAN JUDGMENT</span></div>
   <div className="insightGrid"><div><h2>AI Won&apos;t Replace the Analyst.<br/><em>But It Will Change What a Good Analyst Looks Like.</em></h2><p className="insightLead">AI can accelerate research, requirements, coding, quality checks, and communication—but the analyst remains accountable for the data, methodology, business context, and final recommendation.</p><a className="btn primary" href="https://medium.com/@mackartist/ai-wont-replace-the-analyst-but-it-will-change-what-a-good-analyst-looks-like-69d126a313bb" target="_blank" rel="noreferrer">Read the article on Medium ↗</a></div><aside><p className="eyebrow">THE STANDARD</p><blockquote>Use AI to move faster. Use analytical judgment to decide what is true, what matters, and what should happen next.</blockquote><div className="insightPrinciples"><span>Company-approved tools</span><span>Protected data</span><span>Validated outputs</span><span>Human accountability</span></div></aside></div>
   <div className="insightFooter"><div><small>WHY IT MATTERS</small><p>Strong analysts do more than generate answers. They frame the right problem, challenge assumptions, verify evidence, and communicate decisions responsibly.</p></div><div><small>PRACTICAL APPLICATION</small><p>Requirements discovery · SQL and Python assistance · data-quality analysis · root-cause investigation · executive communication</p></div></div>
  </section>
  <section className="section experience" id="experience"><div className="sticky"><p className="eyebrow blue">04 / EXPERIENCE</p><h2>Built across the healthcare ecosystem.</h2><p>Business analysis grounded in systems, operations, analytics, and accountable delivery.</p></div><div className="timeline">{experience.map((j,i)=><article key={j[1]}><b>0{i+1}</b><div><small>{j[0]}</small><h3>{j[1]}</h3><h4>{j[2]}</h4><p>{j[3]}</p></div></article>)}</div></section>
  <section className="section light credentials"><div><p className="eyebrow blue">05 / CREDENTIALS</p><h2>Always building the next capability.</h2></div><div className="certs">{certifications.map(c=><article key={c.name}><span>GOOGLE</span><h3>{c.name}</h3>{c.url&&<a href={c.url} target="_blank" rel="noreferrer" aria-label={`Verify ${c.name} on Coursera`}>View credential ↗</a>}</article>)}</div></section>
  <section className="section contact" id="contact"><p className="eyebrow">LET&apos;S WORK TOGETHER</p><h2>Turn complexity into<br/><em>measurable results.</em></h2><p>Interested in a senior remote healthcare business analysis, systems, or analytics role? Let&apos;s start a conversation.</p><a className="emailAddress" href="mailto:mackartist@live.com">mackartist@live.com</a><div className="actions"><button className="btn white" type="button" onClick={copyEmail}>{copied?"Email copied ✓":"Copy email address"}</button><a className="btn ghost" target="_blank" rel="noreferrer" href="https://www.linkedin.com/in/steven-gilbert-a7980116a">LinkedIn ↗</a></div><p className="contactHint">Copy the address and paste it into Gmail, Outlook, or your preferred email service.</p></section>
  <div className="siteFooter"><div className="brand"><span>SG</span><b>Steven Gilbert</b></div><p>Senior Healthcare Business Systems Analyst · Data Analytics & BI</p><a href="#top">Back to top ↑</a></div>
 </main>
}
